### ISSUE TITLE
conductor should obey INSECURE_SSL in wskprops

### ISSUE THREAD

**Issue by starpit** [apache/incubator-openwhisk-composer#13]
conductor parses out wskprops, but ignores the INSECURE_SSL setting that might be asserted in that file:
https://github.com/apache/incubator-openwhisk-composer/blob/master/conductor.js#L52-L55

i notice that in the tests, the insecure ssl part is asserted via an env var:
https://github.com/apache/incubator-openwhisk-composer/blob/master/test/conductor.js#L26

i suggest that we should behave as does the go cli, in its INSECURE_SSL behavior.

**Comment by tardieu** [comment]
do you have a pointer to the matching go cli code?

**Comment by tardieu** [comment]
We also need to fix the use of `insecure_certs` at run time (as discussed in #16).

**Comment by dgrove-oss** [comment]
@tardieu -- resolved by #21?

**Comment by tardieu** [comment]
The deploy command now obeys the `__OW_IGNORE_CERTS` environment variable in addition to the `-i` flag as defined by the OpenWhisk client for javascript.

The conductor action code obeys the `$composer.openwhisk.insecure_ssl` invocation parameter.

By default neither deploying, nor running compositions ignores ssl certificate validation failures.
