### ISSUE TITLE
composer should provide an API for generating the conductor action

### ISSUE THREAD

**Issue by lionelvillard** [apache/incubator-openwhisk-composer#17]

**Comment by csantanapr** [comment]
Can you provide more details about the requirement and propose solution?

**Comment by lionelvillard** [comment]
the requirement is to allow third-party tools to programmatically deploy composition. One solution is to extend the composer API exposing `synthesize()`, or better a function combining `compile` and `synthesize`

**Comment by csantanapr** [comment]
Thank you @lionelvillard

**Comment by tardieu** [comment]
Implemented in #22.
