### ISSUE TITLE
composer.parallel not available in openwhisk-composer@0.9.0

### ISSUE THREAD

**Issue by cheukchuen** [apache/incubator-openwhisk-composer#19]
I've tried using the `composer.parallel` combinator that was introduced recently, but it returns `TypeError: composer.parallel is not a function`. I assume they are not packaged into the latest version of `openwhisk-composer`? May I know the estimated time when the module in npm will be updated to include those combinators?

**Comment by tardieu** [comment]
npm supports pulling a module directly from github so you could use that for now. There are only a few minor fixes needed before the next release (doc, ssl certificate, public compilation api) so I am hoping to start the release process in a few days.

**Comment by dgrove-oss** [comment]
composer 0.10.0 was just released with parallel support.
